model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: "gpt-3.5-turbo"
      api_key: os.environ/OPENAI_API_KEY
      rpm: 20
      timeout: 300
      stream_timeout: 60
  - model_name: gpt-4o
    litellm_params:
      model: "gpt-4o"
      api_key: os.environ/OPENAI_API_KEY
      rpm: 20
      timeout: 300
      stream_timeout: 60

general_settings:
  master_key: your-liteLLM-MasterKey
  database_url: "postgresql://root:root@db:5432/litellmdatabase"

litellm_settings:
  drop_params: True
  set_verbose: False
